### PR TITLE
12-feature-1a-useraccount-and-database

### PR DESCRIPTION
**Pull request by lovinalokeswara**
Edited and modified UserAccount feature:
- Added proper documentation the UserAccount object and 
- Created UserManager class to manage UserAccount objects

### CODE REVIEW

**Review by supriyavasanth — DISMISSED** [review]
All documentation looks great and the user manager looks like it should work!

**Review by llukeham — DISMISSED** [review]

**Review by Adelineleonardi — DISMISSED** [review]
Thanks for updating the naming convention, and will try to help with the documentations

**Review by Adelineleonardi — APPROVED** [review]
I resolve the merge conflict and now the naming convention is fixed as well

**Review by llukeham — APPROVED** [review]

**Review by GlassInterface — APPROVED** [review]
Hi Lovina,
This looks good. I see you updated the variable names to better adhere to the CLEAN architecture, but make sure you also refactor the entire code because maybe there are lingering errors somewhere! I will, however, approve it for now since it seems sensible.

**Pull request merged**
