### PR TITLE
51 feature 6 issue 2

### PR DESCRIPTION
**Pull request by llukeham**
Fixed User History UI.

### CODE REVIEW

**Review by lovinalokeswara — CHANGES_REQUESTED** [review]
Hi Luke, I think a class entity should not be called in a UI class, is there a reason why you decided to put them?
image

**Review by Adelineleonardi — DISMISSED** [review]
I see that in your UI u have unlike button, i thought we didn't end up implementing that(?)

**Review by GlassInterface — CHANGES_REQUESTED** [review]
Hi Luke,
I think there are 2 main concerns to address.
Firstly, it would be nice if you could have some JavaDoc on top of each method you define, because it's really hard to tell what each piece of your code is doing at a glance. A bit of comments inside the body of your UI classes may also be nice so that we can tell (at a glance) what each "grouping" of code is building on the screen.
Secondly, like Adeline said, there is not really going to be an unlike button at this point and with what time we have; so, you might want to address your concerns.
However, aside from these, I think that your code is alright.

**Review by GlassInterface — APPROVED** [review]
Hi Luke,
Please see my prior requested changes. I suppose that due to the time crunch it's fine to approve these changes as tentative, but they should be fixed later on.

**Review by supriyavasanth — APPROVED** [review]

**Review by Adelineleonardi — APPROVED** [review]

**Review by supriyavasanth — APPROVED** [review]

**Review by Adelineleonardi — DISMISSED** [review]

**Pull request closed without merging**
