### PR TITLE
Final_feature_login_registration 

### PR DESCRIPTION
**Pull request by llukeham**
Fix package names.
Added subpackages for each layer of data. 
Added back buttons to Search and Filter UI.

### CODE REVIEW

**Review by supriyavasanth — DISMISSED** [review]
Thank you for fixing the naming conventions

**Review by GlassInterface — DISMISSED** [review]
Hi, this looks good to adhere to the naming conventions!

NOTE TO TA: We did this pull request as a group, but we were looking at Luke's screen and providing feedback on how to edit the project as a whole (i.e. codealong).

**Review by Adelineleonardi — APPROVED** [review]

**Review by supriyavasanth — APPROVED** [review]
looks great!

**Review by lovinalokeswara — APPROVED** [review]

**Review by GlassInterface — APPROVED** [review]
Looks good, like we discussed, you just had to change the .Test statements so they would run!
My previous comments still apply.

**Pull request merged**
