### PR TITLE
1 feature 2a search system

### PR DESCRIPTION
**Pull request by ccchwww**
Main functionality for Search and Filter Use cases added.

### CODE REVIEW

**Review by Adelineleonardi — APPROVED** [review]

**Review by GlassInterface — DISMISSED** [review]
Hi Chris, this looks good. It would be nice if you could add comments in a future pull request to the main branch though, as some of the details in FrameworksDrivers and InterfaceAdapters are a bit hard to understand at a glance (for example, it's a bit hard to tell at a glance how you are processing the database).

**Review by lovinalokeswara — DISMISSED** [review]

**Review by Adelineleonardi — APPROVED** [review]

**Review by GlassInterface — CHANGES_REQUESTED** [review]
Hi Chris,
I would want to approve this change, but there are a few compilation errors throughout which would make it difficult for the TA to compile this code. For instance, SexualityFilterType has a naming conflict with UseCase.FilterType. 
In Search.java, public void setPresenter(SearchFilterOutputBoundary presenter) is repeated twice. This causes a compilation error.
Please fix these compilation errors beforehand.

**Review by GlassInterface — APPROVED** [review]
Hi Chris, good work.

**Review by supriyavasanth — APPROVED** [review]
Everything looks good! Try to include javadoc soon.

**Pull request merged**
