### PR TITLE
4 feature 4a recommendation generation

### PR DESCRIPTION
**Pull request by GlassInterface**
This is an interim pull request for the work-in-progress recommendation use case. As discussed with the TA, this particular use case will be updated and checked on Wednesday or Thursday, to be communicated by email notification.

As of now, the recommendation feature includes the main structure of the code in CLEAN architecture with JavaDoc and a list of required changes (mainly adaptations to unexpected deviations from the CRC cards) marked using TODOs.

See the latest commit on this merged branch for more details on what has to be done still.

### CODE REVIEW

**Comment by GlassInterface** [comment]
When merging: you can take your version of the .gitignore. Also, take your version of the UserAccount.java (I had to remove my UserAccount.java for this interim version to be integrated within the main branch without causing compilation errors, it seems).

**Review by Adelineleonardi — DISMISSED** [review]
I saw that you put one of the functions in package tutorial which I believe should not be used, so I guess for next update you can move this function to package that we've made

**Review by lovinalokeswara — DISMISSED** [review]

**Comment by GlassInterface** [comment]
I am currently working on resolving the merge conflicts and updating it so that the merge can work correctly.

**Review by supriyavasanth — APPROVED** [review]

**Review by Adelineleonardi — APPROVED** [review]
I'm not sure why we need oldUserAccount maybe just delete it on your next pull request. I also see TestRecUC class which only consist of comments, if you don't need that maybe u can delete it as well. Overall good job! Good documentation.

**Pull request merged**
